// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_wdensgl
List C_wdensgl(NumericMatrix w, NumericVector beta, NumericMatrix Sigma1, List Sigma2, NumericVector alpha, List Y, NumericMatrix x, NumericMatrix z, int M, int N, IntegerVector ni, int P, int Q);
RcppExport SEXP _nlmm_C_wdensgl(SEXP wSEXP, SEXP betaSEXP, SEXP Sigma1SEXP, SEXP Sigma2SEXP, SEXP alphaSEXP, SEXP YSEXP, SEXP xSEXP, SEXP zSEXP, SEXP MSEXP, SEXP NSEXP, SEXP niSEXP, SEXP PSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma1(Sigma1SEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ni(niSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(C_wdensgl(w, beta, Sigma1, Sigma2, alpha, Y, x, z, M, N, ni, P, Q));
    return rcpp_result_gen;
END_RCPP
}
// C_ll
double C_ll(NumericMatrix knots, NumericMatrix weights, NumericVector beta, NumericMatrix Sigma1, List Sigma2, List Y, NumericMatrix x, NumericMatrix z, int M, int N, IntegerVector ni, int P, int Q, int K);
RcppExport SEXP _nlmm_C_ll(SEXP knotsSEXP, SEXP weightsSEXP, SEXP betaSEXP, SEXP Sigma1SEXP, SEXP Sigma2SEXP, SEXP YSEXP, SEXP xSEXP, SEXP zSEXP, SEXP MSEXP, SEXP NSEXP, SEXP niSEXP, SEXP PSEXP, SEXP QSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma1(Sigma1SEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ni(niSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(C_ll(knots, weights, beta, Sigma1, Sigma2, Y, x, z, M, N, ni, P, Q, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nlmm_C_wdensgl", (DL_FUNC) &_nlmm_C_wdensgl, 13},
    {"_nlmm_C_ll", (DL_FUNC) &_nlmm_C_ll, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_nlmm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
