# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_wdensgl <- function(w, beta, Sigma1, Sigma2, alpha, Y, x, z, M, N, ni, P, Q) {
    .Call(`_nlmm_C_wdensgl`, w, beta, Sigma1, Sigma2, alpha, Y, x, z, M, N, ni, P, Q)
}

C_ll <- function(knots, weights, beta, Sigma1, Sigma2, Y, x, z, M, N, ni, P, Q, K) {
    .Call(`_nlmm_C_ll`, knots, weights, beta, Sigma1, Sigma2, Y, x, z, M, N, ni, P, Q, K)
}

